# Use root/example as user/password credentials
version: "3.9"

services:

  mongo_carrinho:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_carrinho:27017/

  carrinho:
    image: carrinho
    ports:
      - "8000:8000"
    depends_on:
      - mongo_carrinho
    environment:
      DATABASE_URI: "mongodb://root:example@mongo_carrinho:27017/"
